language: objective-c

before_install:
  - git submodule update --init

env:
  matrix:
    - BUILD_SDK_VERSION="8.1" SIMULATOR_VERSION="8.1"
    - BUILD_SDK_VERSION="8.1" SIMULATOR_VERSION="7.1"
    - BUILD_SDK_VERSION="7.1" SIMULATOR_VERSION="7.1"

script: rake

